server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acada
    username: root
    password: JY@class4579

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true